// Front matter so this file shows up in the Gruntwork Service Catalog
:type: service
:name: IAM Users and IAM Groups
:description: Convenient module to manage best practices set of IAM Groups for permissions management, and configuring IAM Users that take advantage of those groups.
:icon: ../../../_docs/aws-organizations-icon.png
:category: Landing Zone
:cloud: aws
:tags: aws-landing-zone, logging, security
:license: gruntwork
:built-with: terraform

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= IAM Users and IAM Groups

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_security"]
image:https://img.shields.io/badge/tf-%3E%3D0.15.0-blue.svg[Terraform version]

This folder contains https://www.terraform.io[Terraform] code to provision and manage best practices set of IAM Groups
for permissions management, and configuring IAM Users that take advantage of those groups.

This feature exists in `account-baseline-security`, but having a separate module to manage IAM Users and Groups is
useful for large scale organizations that frequently:

- Onboard and offboard new users
- Add and remove AWS accounts in their org

The rationale behind this change comes from addressing two issues:

- The cadence of changes for IAM users and groups in the security account is considerably higher than the other things
  that are managed in `account-baseline-security` (e.g., consider CloudTrail, which should only be configured once in
  the lifetime of the account).
- `account-baseline-security` is, by nature, a heavy module that manages tons of resources. Having to go through the
  `plan` and `apply` cycle for all those resources can be very painful, especially for large orgs that need to
  onboard/offboard user frequently.


toc::[]

== Features

* Provision IAM users with default set of IAM Groups, passwords, and access keys.
* Manage a best practices set of IAM Groups for managing different permissions levels in your AWS Account.
* Provision IAM Groups that manage cross account IAM Role access to other accounts in your AWS Organization.


== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/terraform-aws-service-catalog//[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read link:/core-concepts.md[How to use the Gruntwork Service Catalog]!


=== Core concepts

* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/iam-users[iam-users module documentation]:
  Underlying module used to manage the IAM Users from this module.
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/iam-groups[iam-groups module documentation]:
  Underlying module used to manage the IAM Groups from this module.
* link:https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/[How to configure a production-grade AWS account structure]


=== Repo organization

* link:/modules[modules]: the main implementation code for this repo, broken down into multiple standalone, orthogonal submodules.
* link:/examples[examples]: This folder contains working examples of how to use the submodules.
* link:/test[test]: Automated tests for the modules and examples.


== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/for-learning-and-testing/landingzone[examples/for-learning-and-testing/landingzone folder]: The
  `examples/for-learning-and-testing/landingzone` folder contains standalone sample code optimized for learning, experimenting, and
  testing (but not direct production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/examples/for-production[examples/for-production folder]: The `examples/for-production` folder contains sample
  code optimized for direct usage in production. This is code from the
  https://gruntwork.io/reference-architecture/:[Gruntwork Reference Architecture], and it shows you how we build an
  end-to-end, integrated tech stack on top of the Gruntwork Service Catalog.
* link:https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/[How to configure a production-grade AWS account structure]


== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure, feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].


== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes through our automated test suite.

Please see https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library/#contributing-to-the-gruntwork-infrastructure-as-code-library[Contributing to the Gruntwork Infrastructure as Code Library] for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
