// Front matter so this file shows up in the Gruntwork Service Catalog
:type: service
:name: AWS Root Account baseline wrapper
:description: A security baseline for AWS Landing Zone for configuring the root account (AKA master account) of an AWS Organization, including setting up child accounts, AWS Config, AWS CloudTrail, Amazon Guard Duty, IAM users, IAM groups, IAM password policy, and more.
:icon: ../../_docs/aws-organizations-icon.png
:category: Landing Zone
:cloud: aws
:tags: aws-landing-zone, logging, security
:license: gruntwork
:built-with: terraform

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:not-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Account Baseline for root account

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_security"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.0-blue.svg[Terraform version]

A security baseline for AWS Landing Zone for configuring the root account (AKA master account) of an AWS Organization, including setting up
child accounts, AWS Config, AWS CloudTrail, Amazon Guard Duty, IAM users, IAM groups, IAM password policy, and more.

toc::[]

== Features

Get a secure baseline for the root account of your AWS Organization that includes:

* link:/modules/aws-config-multi-region[aws-config-multi-region]
* link:/modules/aws-organizations[aws-organizations]
* link:/modules/aws-organizations-config-rules[aws-organizations-config-rules]
* link:/modules/cloudtrail[cloudtrail]
* link:/modules/cross-account-iam-roles[cross-account-iam-roles]
* link:/modules/guardduty-multi-region[guardduty-multi-region]
* link:/modules/iam-groups[iam-groups]
* link:/modules/iam-user-password-policy[iam-user-password-policy]
* link:/modules/iam-users[iam-users]


== Learn

NOTE: This repo is a part of https://gruntwork.io/infrastructure-as-code-library/[the Gruntwork Infrastructure as Code
Library], a collection of reusable, battle-tested, production ready infrastructure code. If you've never used the Infrastructure as Code Library before, make sure to read https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library/[How to use the Gruntwork Infrastructure as Code Library]!


=== Core concepts

* Learn more about each individual module, click the link in the link:#features[Features] section.
* link:https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/[How to configure a production-grade AWS account structure]


=== Repo organization

* link:/modules[modules]: the main implementation code for this repo, broken down into multiple standalone, orthogonal submodules.
* link:/codegen[codegen]: Code generation utilities that help generate modules in this repo.
* link:/examples[examples]: This folder contains working examples of how to use the submodules.
* link:/test[test]: Automated tests for the modules and examples.


== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/account-baseline-root[examples/account-baseline-root]: The `examples/account-baseline-root`
folder contains sample code optimized for learning, experimenting, and testing (but not production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* **_Coming soon_**. We have not yet added this module to the
  https://github.com/gruntwork-io/infrastructure-modules-multi-account-acme[Acme example Reference Architecture].
* link:https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/[How to configure a production-grade AWS account structure]


== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure, feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].


== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes through our automated test suite.

Please see https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library/#contributing-to-the-gruntwork-infrastructure-as-code-library[Contributing to the Gruntwork Infrastructure as Code Library] for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
