repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "2520157"
    hooks:
      - id: terraform-fmt
      - id: terragrunt-hclfmt
      - id: check-terratest-skip-env

  - repo: local
    hooks:
      - id: validate-test-mappings
        name: validate-test-mappings
        entry: ./hooks/run_validate_test_mappings.sh
        language: script
        files: "$^"
        always_run: true
        pass_filenames: false
