repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.4
    hooks:
      - id: terraform-fmt
      - id: terragrunt-hclfmt

  - repo: local
    hooks:
      - id: validate-test-mappings
        name: validate-test-mappings
        entry: ./hooks/run_validate_test_mappings.sh
        language: script
        files: "$^"
        always_run: true
        pass_filenames: false
      - id: check-skip-env
        name: check-skip-env
        entry: ./hooks/run_check_skip_env.sh
        language: script
        files: test/.*\.go$
