// Front matter so this file shows up in the Gruntwork Service Catalog
:type: service
:name: AWS Security Account baseline wrapper
:description: A security baseline for AWS Landing Zone for configuring the security account (the one where all your IAM users and IAM groups are defined), including setting up AWS Config, AWS CloudTrail, Amazon Guard Duty, IAM users, IAM groups, IAM password policy, and more.
:icon: ../../../_docs/aws-organizations-icon.png
:category: Landing Zone
:cloud: aws
:tags: aws-landing-zone, logging, security
:license: gruntwork
:built-with: terraform

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Account Baseline for security account

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_security"]
image:https://img.shields.io/badge/tf-%3E%3D0.15.0-blue.svg[Terraform version]

A security baseline for AWS Landing Zone for configuring the security account (the one where all your IAM users and IAM groups are defined), including setting up
AWS Config, AWS CloudTrail, Amazon Guard Duty, IAM users, IAM groups, IAM password policy, and more.

toc::[]

== Features

Get a secure baseline for the security account of your AWS Organization that includes:

* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/aws-config-multi-region[aws-config-multi-region]
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/cloudtrail[cloudtrail]
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/cross-account-iam-roles[cross-account-iam-roles]
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/guardduty-multi-region[guardduty-multi-region]
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/iam-groups[iam-groups]
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/iam-users[iam-users]
* https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/iam-user-password-policy[iam-user-password-policy]


== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/terraform-aws-service-catalog//[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read link:/core-concepts.md[How to use the Gruntwork Service Catalog]!


=== Core concepts

* Learn more about each individual module, click the link in the link:#features[Features] section.
* link:https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/[How to configure a production-grade AWS account structure]


=== Repo organization

* link:/modules[modules]: the main implementation code for this repo, broken down into multiple standalone, orthogonal submodules.
* link:/examples[examples]: This folder contains working examples of how to use the submodules.
* link:/test[test]: Automated tests for the modules and examples.


== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/for-learning-and-testing/landingzone[examples/for-learning-and-testing/landingzone folder]: The
  `examples/for-learning-and-testing/landingzone` folder contains standalone sample code optimized for learning, experimenting, and
  testing (but not direct production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/examples/for-production[examples/for-production folder]: The `examples/for-production` folder contains sample
  code optimized for direct usage in production. This is code from the
  https://gruntwork.io/reference-architecture/:[Gruntwork Reference Architecture], and it shows you how we build an
  end-to-end, integrated tech stack on top of the Gruntwork Service Catalog.
* link:https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/[How to configure a production-grade AWS account structure]


== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure, feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].


== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes through our automated test suite.

Please see https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library/#contributing-to-the-gruntwork-infrastructure-as-code-library[Contributing to the Gruntwork Infrastructure as Code Library] for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
