defaults: &defaults
  machine:
    enabled: true
    image: "ubuntu-1604:201903-01"
  environment:
    GRUNTWORK_INSTALLER_VERSION: v0.0.21
    TERRATEST_LOG_PARSER_VERSION: v0.13.24
    KUBERGRUNT_VERSION: v0.5.11
    K8S_VERSION: v1.15.0
    MODULE_CI_VERSION: v0.16.1
    TERRAFORM_VERSION: 0.12.21
    PACKER_VERSION: 1.5.4
    GOLANG_VERSION: 1.13.8
    KUBECONFIG: /home/circleci/.kube/config

install_gruntwork_utils: &install_gruntwork_utils
  name: install gruntwork utils
  command: |
    curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
    gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
    gruntwork-install --binary-name "kubergrunt" --repo "https://github.com/gruntwork-io/kubergrunt" --tag "${KUBERGRUNT_VERSION}"
    configure-environment-for-gruntwork-module \
      --terraform-version ${TERRAFORM_VERSION} \
      --packer-version ${PACKER_VERSION} \
      --go-version ${GOLANG_VERSION}

install_kube_utils: &install_kube_utils
  name: install kubernetes utilities
  command: |
    # Install kubectl
    curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/

    # Make sure the kube config directory and file exists
    mkdir -p "$(dirname ${KUBECONFIG})"
    touch "${KUBECONFIG}"

version: 2.0
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      # Install kubernetes utilities
      - run:
          <<: *install_kube_utils

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/logs
            pyenv global 3.5.2
            python ./.circleci/run-tests.py | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - run:
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          <<: *install_gruntwork_utils

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
