version: 2.1

# ---------------------------------------------------------------------------------------------------------------------
# REUSABLE ALIASES
# ---------------------------------------------------------------------------------------------------------------------

defaults: &defaults
  machine:
    enabled: true
    image: "ubuntu-1604:201903-01"
  environment:
    GRUNTWORK_INSTALLER_VERSION: v0.0.21
    TERRATEST_LOG_PARSER_VERSION: v0.13.24
    KUBERGRUNT_VERSION: v0.5.11
    K8S_VERSION: v1.15.0
    MODULE_CI_VERSION: v0.18.4
    TERRAFORM_VERSION: 0.12.21
    PACKER_VERSION: 1.5.4
    GOLANG_VERSION: 1.13.8
    KUBECONFIG: /home/circleci/.kube/config

install_gruntwork_utils: &install_gruntwork_utils
  name: install gruntwork utils
  command: |
    curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
    gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --module-name "terraform-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
    gruntwork-install --binary-name "kubergrunt" --repo "https://github.com/gruntwork-io/kubergrunt" --tag "${KUBERGRUNT_VERSION}"
    configure-environment-for-gruntwork-module \
      --terraform-version ${TERRAFORM_VERSION} \
      --packer-version ${PACKER_VERSION} \
      --go-version ${GOLANG_VERSION}

install_kube_utils: &install_kube_utils
  name: install kubernetes utilities
  command: |
    # Install kubectl
    curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/

    # Make sure the kube config directory and file exists
    mkdir -p "$(dirname ${KUBECONFIG})"
    touch "${KUBECONFIG}"

run_pre_commit: &run_pre_commit
  # Fail the build if the pre-commit hooks don't pass. Note: if you run pre-commit install locally, these hooks will
  # execute automatically every time before you commit, ensuring the build never fails at this step!
  name: run pre-commit hooks
  command: |
    pip install pre-commit==1.11.2 cfgv==2.0.1
    pre-commit install
    pre-commit run --all-files

run_circleci_unit_tests: &run_circleci_unit_tests
  name: run circleci unit tests
  command: |
    pyenv global 3.5.2
    python ./.circleci/run_tests_unit_tests.py

# ---------------------------------------------------------------------------------------------------------------------
# REUSABLE STEPS
# ---------------------------------------------------------------------------------------------------------------------

commands:
  prepare_environment_and_run_prechecks:
    description: "Prepare the environment by installing necessary tools, and run preflight checks before main tests"
    steps:
      - run:
          <<: *install_gruntwork_utils
      - run:
          <<: *install_kube_utils
      - run:
          <<: *run_pre_commit
      - run:
          <<: *run_circleci_unit_tests
      - run: mkdir -p /tmp/logs
  store_results:
    description: "Store test results for easy viewing."
    steps:
      - run:
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

# ---------------------------------------------------------------------------------------------------------------------
# BUILD JOBS
# ---------------------------------------------------------------------------------------------------------------------

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - prepare_environment_and_run_prechecks

      - run:
          name: run tests
          command: |
            pyenv global 3.5.2
            test_regex=""
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              # On master, the last commit is the merge commit which contains all the changes
              test_regex="$(python ./.circleci/run_tests.py --source-ref 'HEAD^')"
            else
              test_regex="$(python ./.circleci/run_tests.py)"
            fi
            run-go-tests --path ./test --timeout 1h --packages "-run \"$test_regex\"" | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - store_results


  run_all_tests:
    <<: *defaults
    steps:
      - checkout

      - prepare_environment_and_run_prechecks

      - run:
          name: run tests
          command: |
            run-go-tests --path ./test --timeout 1h | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - store_results

  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          <<: *install_gruntwork_utils

# ---------------------------------------------------------------------------------------------------------------------
# WORKFLOWS
# ---------------------------------------------------------------------------------------------------------------------

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - run_all_tests
