version: 2.1

# ---------------------------------------------------------------------------------------------------------------------
# REUSABLE ALIASES
# ---------------------------------------------------------------------------------------------------------------------

defaults: &defaults
  resource_class: xlarge
  machine:
    enabled: true
    image: "ubuntu-1604:201903-01"
  <<: *env

env: &env
  environment:
    # renovate.json auto-update: gruntwork-installer
    GRUNTWORK_INSTALLER_VERSION: v0.0.29
    # renovate.json auto-update: terratest
    TERRATEST_LOG_PARSER_VERSION: v0.30.23
    # renovate.json auto-update: kubergrunt
    KUBERGRUNT_VERSION: v0.6.4
    # renovate.json auto-update: module-ci
    MODULE_CI_VERSION: v0.29.1
    # renovate.json auto-update: terragrunt
    TERRAGRUNT_VERSION: v0.26.4
    # renovate.json auto-update-github-releases: hashicorp/terraform
    TERRAFORM_VERSION: 0.12.28
    # We intentionally do NOT auto update K8S, as it should be tied to EKS versions, and our support for them in
    # terraform-aws-eks, both of which lag behind open source K8S
    K8S_VERSION: v1.15.0
    # renovate.json auto-update-github-releases: hashicorp/packer
    PACKER_VERSION: 1.6.5
    # TODO: how to get renovate.json to auto-update the Go version? They publish tags, but they are of a strange format
    # like "go1.15": https://github.com/golang/go/releases
    GOLANG_VERSION: 1.14.9
    # renovate.json auto-update-github-tags: github/hub
    HUB_VERSION: 2.14.2
    MINIKUBE_VERSION: v1.11.0
    KUBECONFIG: /home/circleci/.kube/config
    # The GOPRIVATE environment variable controls which modules the go command considers to be private
    # (not available publicly) and should therefore not use the proxy or checksum database.
    # Without this, tests fail with a "410 Gone" error
    GOPRIVATE: github.com/gruntwork-io

install_gruntwork_utils: &install_gruntwork_utils
  name: install gruntwork utils
  command: |
    curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
    gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --module-name "terraform-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
    gruntwork-install --module-name "kubernetes-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "kubergrunt" --repo "https://github.com/gruntwork-io/kubergrunt" --tag "${KUBERGRUNT_VERSION}"
    configure-environment-for-gruntwork-module \
      --terraform-version ${TERRAFORM_VERSION} \
      --terragrunt-version ${TERRAGRUNT_VERSION} \
      --packer-version ${PACKER_VERSION} \
      --go-version ${GOLANG_VERSION}

install_kube_utils: &install_kube_utils
  name: install kubernetes utilities
  command: |
    # Install kubectl
    curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/

    # Make sure the kube config directory and file exists
    mkdir -p "$(dirname ${KUBECONFIG})"
    touch "${KUBECONFIG}"

    # Install and boot up minikube
    setup-minikube --minikube-version "${MINIKUBE_VERSION}" --k8s-version "${K8S_VERSION}"

install_hub_cli: &install_hub_cli
  name: install hub CLI
  command: |
    curl -Lo hub.tgz "https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-amd64-${HUB_VERSION}.tgz"
    tar -xf hub.tgz
    sudo mv "hub-linux-amd64-${HUB_VERSION}/bin/hub" /usr/local/bin
    sudo chmod +x /usr/local/bin/hub
    echo 'export GITHUB_TOKEN="$GITHUB_OAUTH_TOKEN"' >> $BASH_ENV

run_pre_commit: &run_pre_commit
  # Fail the build if the pre-commit hooks don't pass. Note: if you run pre-commit install locally, these hooks will
  # execute automatically every time before you commit, ensuring the build never fails at this step!
  name: run pre-commit hooks
  command: |
    pip install pre-commit
    pre-commit install
    pre-commit run --all-files

run_circleci_unit_tests: &run_circleci_unit_tests
  name: run circleci unit tests
  command: python ./.circleci/run_tests_unit_tests.py

# CIRCLE_PR_NUMBER is only available on forked repos, so we extract if from the PR URL.
set_pr_number: &set_pr_number
  name: Set PR number
  command: |
      echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV

# ---------------------------------------------------------------------------------------------------------------------
# REUSABLE STEPS
# ---------------------------------------------------------------------------------------------------------------------

commands:
  prepare_environment:
    description: "Prepare the environment by installing necessary tools, and run preflight checks before main tests"
    steps:
      - run:
          <<: *set_pr_number
      - run:
          <<: *install_gruntwork_utils
      - run:
          <<: *install_kube_utils
      - run:
          <<: *install_hub_cli
      - run: mkdir -p /tmp/logs
  store_results:
    description: "Store test results for easy viewing."
    steps:
      - run:
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

# ---------------------------------------------------------------------------------------------------------------------
# BUILD JOBS
# ---------------------------------------------------------------------------------------------------------------------

jobs:
  precommit:
    <<: *env
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          <<: *install_gruntwork_utils
      - run:
          <<: *run_pre_commit
      - run:
          <<: *run_circleci_unit_tests

  test:
    <<: *defaults
    steps:
      - checkout

      - prepare_environment

      - run:
          name: find all tests to run
          command: |
            pyenv global 3.5.2
            test_regex=""
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              # On master, the last commit is the merge commit which contains all the changes
              test_regex="$(python ./.circleci/run_tests.py --source-ref 'HEAD^' 2> debug.log)"
            else
              test_regex="$(python ./.circleci/run_tests.py 2> debug.log)"
            fi
            cat debug.log
            echo "export TEST_REGEX='$test_regex'" >> $BASH_ENV

            # Comment the debug log on GitHub if there is a PR number
            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
              echo -e "Tests run for build [$CIRCLE_BUILD_NUM]($CIRCLE_BUILD_URL)\n\`\`\`\n$(cat debug.log)\n\`\`\`" \
                | hub api repos/{owner}/{repo}/issues/"$CIRCLE_PR_NUMBER"/comments --field body=@-
            fi

      - run:
          name: run tests
          command: |
            run-go-tests --path ./test --timeout 2h --packages "-run '$TEST_REGEX'" | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - store_results


  run_all_tests:
    <<: *defaults
    steps:
      - checkout

      - prepare_environment

      - run:
          name: run tests
          command: |
            run-go-tests --path ./test --timeout 2h | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - store_results

  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          <<: *install_gruntwork_utils

# ---------------------------------------------------------------------------------------------------------------------
# WORKFLOWS
# ---------------------------------------------------------------------------------------------------------------------

workflows:
  version: 2
  build-and-test:
    jobs:
      - precommit:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - precommit
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
