version: '2.0'
services:
  tls:
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
    entrypoint: /scripts/create-tls-cert.sh
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - UID
    user: "${UID}:${UID}"
    volumes:
      - ./tmp:/tmp
      # TODO: remove
      - .:/scripts # only for development
  rds:
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
    entrypoint: /scripts/download-rds-ca-certs.sh
    volumes:
      - ./tmp:/tmp
      # TODO: remove
      - .:/scripts # only for development
  trust-stores:
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
    entrypoint: /scripts/generate-trust-stores.sh
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - ./tmp:/tmp
      # TODO: remove
      - .:/scripts # only for development
