version: '2.0'
services:
  certs:
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
    image: tls-scripts_certs
    entrypoint: create-tls-cert.sh
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - ./tls:/tls
  rds:
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
    image: tls-scripts_rds
    entrypoint: download-rds-ca-certs.sh
    volumes:
      - ./tls:/tls
  trust-stores:
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
    image: tls-scripts_trust-stores
    entrypoint: generate-trust-stores.sh
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - ./tls:/tls
