:type: module
:name: TLS Scripts
:description: Create TLS certificates, download CA certs for RDS, and generate trust stores.
:icon: // TODO
:category: tools
:cloud: aws
:tags: TLS, SSL, certificates, certificate authority, trust store, key store
:license: gruntwork
:built-with: terraform, bash, docker

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= TLS Scripts

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_service_catalog"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.0-blue.svg[Terraform version]

This folder contains code to generate TLS certificates and trust stores, and download RDS CA certificates from AWS.

toc::[]




== Features

Bash scripts that simplify working with TLS certificates. You will typically only need
these scripts to configure end-to-end encryption in your Reference Architecture.




== About these scripts

=== Create TLS Cert

This script will automatically create a CA cert and a TLS cert signed by that CA, assuming
those certs don't already exist. The TLS cert private key is encrypted with `gruntkms`.

Optionally with the `--upload-to-iam` flag, this script can also upload the cert to IAM, so it can be used with an ELB or ALB.
These certs are meant for private/internal use only, such as to set up end-to-end encryption within an AWS account.
The only IP address in the cert will be 127.0.0.1 and localhost, so you can test your servers locally.
You can also use the servers with the ELB or ALB, as the AWS load balancers don't verify the CA.
Also see [Loading TLS secrets from AWS Secrets Manager](https://github.com/gruntwork-io/aws-sample-app/blob/master/core-concepts.md#loading-tls-secrets-from-aws-secrets-manager)

=== Download RDS CA Certificates
This script downloads the Certificate Authority certs for RDS so that applications can validate the certs when
connecting to RDS over TLS.

=== Generate Trust Stores
This script automatically generates a Key Store and Trust Store, which are typically used with Java apps to securely
store TLS certificates. If they don't already exist, the Key Store, Trust Store, and public cert / CA will be generated
to the specified paths, and the Key Store password will be stored in AWS Secrets Manager. The script writes the KMS-encrypted
password for the Key Store to `stdout`.



== Running these scripts in Docker

We've provided a `Dockerfile` in this module for you to use for both running and testing the TLS scripts.
Open a terminal in this directory and run `docker build -t {image name} --build-arg BITHUB_OAUTH_TOKEN={your github-oauth-token} .` to create a docker container with all the dependencies needed to run the scripts and the tests.
Then you can run `docker run --rm -it {image name} bash` to run the scripts interactively in the container and check their outputs.

=== Create TLS Cert

For example, to run the `create-tls-cert.sh` script interactively in Docker, you'll have to pass in environment variables to the `run` command.

[source,bash]
----
docker run --rm -it -e AWS_ACCESS_KEY_ID={your key id} -e AWS_SECRET_ACCESS_KEY={your secret key} {image name} bash
----

Then while in the container's shell, you can run the example call, which doesn't upload the cert to IAM:

[source,bash]
----
create-tls-cert.sh --ca-path ca.crt.pem --cert-path my-app.crt.pem --key-path my-app.key.pem.kms.encrypted --company-name Acme --kms-key-id alias/cmk-dev --aws-region us-east-1
----

The generated cert files are located in `/tmp/vault-blueprint/modules/private-tls-cert/`.

To upload the cert to IAM, include the `--upload-to-iam` flag along with the correct KMS key id in `--kms-key-id`, and the correct region for that key in `--aws-region`. The cert is uploaded to IAM as a Server Certificate, which cannot be managed using the AWS Console UI. You must use the AWS API to upload, update, and delete these certs.


=== Download RDS CA Cert

=== Generate Trust Stores


== Testing these scripts in Docker

=== Create TLS Cert

=== Download RDS CA Cert

=== Generate Trust Stores


== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/aws-service-catalog/[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read https://gruntwork.io/guides/foundations/how-to-use-gruntwork-service-catallog/[How to use the Gruntwork
Service Catalog]!







== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers
https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork
customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure,
feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].




== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even
contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes
through our automated test suite.

Please see
https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library#_contributing_to_the_gruntwork_infrastructure_as_code_library[Contributing to the Gruntwork Service Catalog]
for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
