:type: service
:name: EC2 Instance
:description: Deploy an EC2 Instance, including server hardening, IAM role, EIP, EBS Volume, and CloudWatch metrics, logs, and alerts.
:icon: /_docs/bastion-icon.png
:category: services
:cloud: aws
:tags: ec2, ssh, security
:license: gruntwork
:built-with: terraform, bash, packer

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= EC2 Instance

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_service_catalog"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.0-blue.svg[Terraform version]

This Terraform Module creates a single EC2 instance that includes server hardening, IAM role, EIP (optional), EBS Volume (optional), and CloudWatch metrics, logs, and alerts. Note that a single EC2 instance can be a single point of failure, so if you want to run multiple EC2 instances for high availability and scalability, see the [asg-service](/modules/services/asg-service).

toc::[]

== Features

* Build an AMI to run on the EC2 instance
* Create EC2 instance for the host
* Allocate an optional Elastic IP Address (EIP) and an associated DNS record
* Create an IAM Role and IAM instance profile
* Create a security group to manage ingress and egress traffic on desired ports
* Harden the OS by installing `fail2ban`, `ntp`, `auto-update`, `ip-lockdown`, and more
* Send all logs and metrics to CloudWatch
* Configure alerts in CloudWatch for CPU, memory, and disk space usage
* Manage SSH access with IAM groups using `ssh-grunt`
* Create and mount optional EBS volumes
* Allow ingress traffic on desired ports

== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/terraform-aws-service-catalog/[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read https://gruntwork.io/guides/foundations/how-to-use-gruntwork-service-catalog/[How to use the Gruntwork
Service Catalog]!

=== Core concepts

* link:core-concepts.md#how-do-i-update-my-instance[How do I update my instance?]
* link:core-concepts.md#how-do-i-use-user-data[How do I use User Data?]
* link:core-concepts.md#how-do-i-mount-an-ebs-volume[How do I mount an EBS volume?]

=== The EC2 Instance AMI

The EC2 Instance AMI is defined using the https://www.packer.io/[Packer] template at `ec2-instance.json`.
This template configures the AMI to:

1. Run the https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/ssh-grunt[ssh-grunt module] so that
   developers can upload their public SSH keys to IAM and use those SSH keys, along with their IAM user names, to SSH
   to the EC2 instance.
1. Run the https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/auto-update[auto-update module] so
   that the EC2 instance installs security updates automatically.
1. Optionally run the https://github.com/gruntwork-io/terraform-aws-monitoring/tree/master/modules/logs/syslog[syslog module] to automatically rotate and rate limit syslog so that the EC2 instance doesn't run out of disk space from large volumes of logs.

== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/for-learning-and-testing[examples/for-learning-and-testing folder]: The
  `examples/for-learning-and-testing` folder contains standalone sample code optimized for learning, experimenting, and
  testing (but not direct production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/examples/for-production[examples/for-production folder]: The `examples/for-production` folder contains sample
  code optimized for direct usage in production. This is code from the
  https://gruntwork.io/reference-architecture/:[Gruntwork Reference Architecture], and it shows you how we build an
  end-to-end, integrated tech stack on top of the Gruntwork Service Catalog.
  configure CI / CD for your apps and infrastructure.


== Operate

=== Day-to-day operations

* https://github.com/fail2ban/fail2ban[`fail2ban`] bans IP addresses that cause too many failed login attempts. The EC2 instance is configured with `fail2ban` as a security measure. See the  https://github.com/gruntwork-io/terraform-aws-security/tree/master/modules/fail2ban[`fail2ban` module] for more information.


== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers
https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork
customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure,
feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].


== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even
contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes
through our automated test suite.

Please see
https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library#_contributing_to_the_gruntwork_infrastructure_as_code_library[Contributing to the Gruntwork Service Catalog]
for instructions.


== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
