:type: service
:name: Gruntwork Access
:description: Grant the Gruntwork team access to one of your AWS accounts so we can deploy a Reference Architecture for you or help with troubleshooting!
:icon: /_docs/grunty-icon.jpeg
:category: remote-access
:cloud: aws
:tags: reference-architecture, troubleshooting
:license: gruntwork
:built-with: terraform

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Gruntwork Access

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_service_catalog"]
image:https://img.shields.io/badge/tf-%3E%3D0.15.0-blue.svg[Terraform version]

You can use this Terraform module to grant the Gruntwork team access to your AWS account to for either:

. Deploying a https://gruntwork.io/reference-architecture/[Reference Architecture].
. Helping your team with troubleshooting.

Under the hood, this module creates an https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html[IAM Role] in your
AWS account that the Gruntwork team can assume. This allows the Gruntwork team to securely access your AWS accounts
without having to create, share, or manage credentials.


toc::[]

== Features

* Create an IAM role that grants Gruntwork access to your AWS accounts
* Choose the Managed IAM Policy to grant
* Require MFA for assuming the IAM role
* Grant access to your own security account (required for Reference Architecture deployments)

== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/terraform-aws-service-catalog/[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read https://gruntwork.io/guides/foundations/how-to-use-gruntwork-service-catalog/[How to use the Gruntwork
Service Catalog]!

=== Core concepts

* https://gruntwork.io/reference-architecture/[What is the Gruntwork Reference Architecture?]

== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/for-learning-and-testing[examples/for-learning-and-testing folder]: The
`examples/for-learning-and-testing` folder contains standalone sample code optimized for learning, experimenting, and
testing (but not direct production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/examples/for-production[examples/for-production folder]: The `examples/for-production` folder contains sample
code optimized for direct usage in production. This is code from the
https://gruntwork.io/reference-architecture/:[Gruntwork Reference Architecture], and it shows you how we build an
end-to-end, integrated tech stack on top of the Gruntwork Service Catalog.
configure CI / CD for your apps and infrastructure.



== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers
https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork
customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure,
feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].


== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even
contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes
through our automated test suite.

Please see
https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library#_contributing_to_the_gruntwork_infrastructure_as_code_library[Contributing to the Gruntwork Service Catalog]
for instructions.


== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
