:type: service
:name: Amazon Elasticsearch
:description: Deploy and manage Amazon Elasticsearch Service
:icon: /_docs/aes-icon.png
:category: database
:cloud: aws
:tags: analytics, data
:license: gruntwork
:built-with: terraform

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Amazon Elasticsearch Service

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_service_catalog"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.0-blue.svg[Terraform version]

This folder contains code to deploy an Amazon Elasticsearch Service cluster managed by AWS.

Amazon Elasticsearch Service makes it easy to deploy, operate, and scale Elasticsearch. It is a fully managed service that delivers Elasticsearch’s easy-to-use APIs and real-time capabilities along with the availability, scalability, and security required by production workloads. For more information about Elasticsearch and its uses, see the http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html[Amazon Elasticsearch Service developer guide] and the https://aws.amazon.com/elasticsearch-service/getting-started/[Getting Started] page.

toc::[]



== Features

* Deploy a fully-managed native Elasticsearch cluster in a VPC
* Use VPC-based security
    * If you use AWS's default VPC, which contains public subnets, your Elasticsearch cluster is still only accessible from within the VPC. It is not publicly accessible. https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html#es-vpc-security[See these docs] for more information.
* Leverage zone awareness, i.e., deployment of Elasticsearch nodes across Availability Zones
* Automatic nightly snapshots
* CloudWatch Alarms for alerting when CPU, memory, and disk metrics exceed certain thresholds


== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/aws-service-catalog//[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read https://gruntwork.io/guides/foundations/how-to-use-gruntwork-service-catallog/[How to use the Gruntwork
Service Catalog]!

=== Introductory documentation:
* https://aws.amazon.com/elasticsearch-service/[About Amazon Elasticsearch Service]
* https://aws.amazon.com/elasticsearch-service/features/[Features of Amazon ES]
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html[Developer Guide]: Contains the main documentation on how to use Amazon ES and answers questions such as "What is Amazon Elasticsearch Service?"
* https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_ES_Stream.html[Streaming CloudWatch monitoring logs to Amazon Elasticsearch Service]



== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/for-learning-and-testing[examples/for-learning-and-testing folder]: The
  `examples/for-learning-and-testing` folder contains standalone sample code optimized for learning,
  experimenting, and testing (but not direct production usage).
* https://aws.amazon.com/free/[AWS Free tier]: Using Amazon ES on Amazon's free tier is a great way to get started, but it has limited features and does not include encryption at rest, ultra warm data notes, or advanced security options such as fine-grained access control. The free tier does allow multiple availability zones, VPC-based access control, TLS-only requests, and node-to-node encryption.


=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/examples/for-production[examples/for-production folder]: The `examples/for-production` folder contains sample
  code optimized for direct usage in production. This is code from the
  https://gruntwork.io/reference-architecture/:[Gruntwork Reference Architecture], and it shows you how we build an
  end-to-end, integrated tech stack on top of the Gruntwork Service Catalog.
* https://aws.amazon.com/elasticsearch-service/pricing/[Amazon Elasticsearch Service pricing]




== Operate

=== Day-to-day operations
* https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/index-data/[Open Distro docs: How to index data into Elasticsearch]: Documentation by Open Distro for Elasticsearch, a reliable resource on how to use Elasticsearch APIs.
* https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html[Elastic docs: How to index data into Elasticsearch]: Documentation by Elastic, the originators of Elasticsearch.
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/sizing-domains.html[How to size Amazon ES domains]

=== Major changes

* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html[Upgrading Elasticsearch]
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html[Using Snapshot / Restore]




== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers
https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork
customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure,
feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].




== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even
contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes
through our automated test suite.

Please see
https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library#_contributing_to_the_gruntwork_infrastructure_as_code_library[Contributing to the Gruntwork Service Catalog]
for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
