:type: service
:name: Amazon Elasticsearch
:description: Deploy and manage Amazon Elasticsearch Service (AES)
:icon: /_docs/aes-icon.png
:category: database
:cloud: aws
:tags: analytics, data
:license: gruntwork
:built-with: terraform

// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Amazon Elasticsearch Service

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_service_catalog"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.0-blue.svg[Terraform version]

This folder contains code to deploy an Amazon Elasticsearch Service (AES) cluster managed by AWS.

toc::[]



== Features

TODO: replace
* Deploy a fully-managed native Elasticsearch cluster
* Supports zone awareness, i.e., deployment of Elasticsearch nodes across Availability Zones.
* Read replicas
* Automatic nightly snapshots
* Automatic cross account snapshots
* Automatic scaling of storage
* CloudWatch Alarms for alerting when CPU, memory, and disk metrics exceed certain thresholds
* CloudWatch dashboard widgets for AES statistics


== Learn

NOTE: This repo is a part of the https://github.com/gruntwork-io/aws-service-catalog//[Gruntwork Service Catalog], a collection of
reusable, battle-tested, production ready infrastructure code. If you've never used the Service Catalog before, make
sure to read https://gruntwork.io/guides/foundations/how-to-use-gruntwork-service-catallog/[How to use the Gruntwork
Service Catalog]!

TODO: replace
* https://github.com/gruntwork-io/module-data-storage/blob/master/modules/rds/core-concepts.md#what-is-amazon-rds[What is Amazon RDS?]
* https://github.com/gruntwork-io/module-data-storage/blob/master/modules/rds/core-concepts.md#common-gotchas[Common gotchas with RDS]
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html[RDS documentation]: Amazon's docs for RDS that
  cover core concepts such as the types of databases supported, security, backup & restore, and monitoring.
* _https://dataintensive.net[Designing Data Intensive Applications]_: the best book we've found for understanding data
  systems, including relational databases, NoSQL, replication, sharding, consistency, and so on.



== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples/for-learning-and-testing[examples/for-learning-and-testing folder]: The
  `examples/for-learning-and-testing` folder contains standalone sample code optimized for learning, experimenting, and
  testing (but not direct production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/examples/for-production[examples/for-production folder]: The `examples/for-production` folder contains sample
  code optimized for direct usage in production. This is code from the
  https://gruntwork.io/reference-architecture/:[Gruntwork Reference Architecture], and it shows you how we build an
  end-to-end, integrated tech stack on top of the Gruntwork Service Catalog.




== Operate

=== Day-to-day operations

TODO: replace
* https://github.com/gruntwork-io/module-data-storage/blob/master/modules/rds/core-concepts.md#how-do-you-connect-to-the-database[How to connect to an RDS instance]
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAM.html[How to authenticate to RDS with IAM]
* https://github.com/gruntwork-io/module-data-storage/blob/master/modules/rds/core-concepts.md#how-do-you-scale-this-database[How to scale RDS]
* https://github.com/gruntwork-io/module-data-storage/blob/master/modules/lambda-create-snapshot/core-concepts.md#data-backup-core-concepts[How to back up RDS databases]
* https://github.com/gruntwork-io/module-data-storage/blob/master/modules/lambda-cleanup-snapshots/README.md[How clean up old database snapshots]
* link:core-concepts.md#how-do-i-use-kubernetes-service-discovery-with-the-rds-database[How do I use Kubernetes Service
  Discovery with the RDS database?]

=== Major changes

TODO: replace
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html[Upgrading a DB instance]
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RestoreFromSnapshot.html[Restoring from a DB snapshot]




== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers
https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork
customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure,
feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].




== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even
contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes
through our automated test suite.

Please see
https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library#_contributing_to_the_gruntwork_infrastructure_as_code_library[Contributing to the Gruntwork Service Catalog]
for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.
